/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { InstrumentService } from "../instrument.service";
import { InstrumentCreateInput } from "./InstrumentCreateInput";
import { Instrument } from "./Instrument";
import { InstrumentFindManyArgs } from "./InstrumentFindManyArgs";
import { InstrumentWhereUniqueInput } from "./InstrumentWhereUniqueInput";
import { InstrumentUpdateInput } from "./InstrumentUpdateInput";
import { TransactionFindManyArgs } from "../../transaction/base/TransactionFindManyArgs";
import { Transaction } from "../../transaction/base/Transaction";
import { TransactionWhereUniqueInput } from "../../transaction/base/TransactionWhereUniqueInput";

export class InstrumentControllerBase {
  constructor(protected readonly service: InstrumentService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Instrument })
  async createInstrument(
    @common.Body() data: InstrumentCreateInput
  ): Promise<Instrument> {
    return await this.service.createInstrument({
      data: data,
      select: {
        createdAt: true,
        currencyId: true,
        exchangeId: true,
        id: true,
        instrumentId: true,
        instrumentTypeId: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Instrument] })
  @ApiNestedQuery(InstrumentFindManyArgs)
  async instruments(@common.Req() request: Request): Promise<Instrument[]> {
    const args = plainToClass(InstrumentFindManyArgs, request.query);
    return this.service.instruments({
      ...args,
      select: {
        createdAt: true,
        currencyId: true,
        exchangeId: true,
        id: true,
        instrumentId: true,
        instrumentTypeId: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Instrument })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async instrument(
    @common.Param() params: InstrumentWhereUniqueInput
  ): Promise<Instrument | null> {
    const result = await this.service.instrument({
      where: params,
      select: {
        createdAt: true,
        currencyId: true,
        exchangeId: true,
        id: true,
        instrumentId: true,
        instrumentTypeId: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Instrument })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateInstrument(
    @common.Param() params: InstrumentWhereUniqueInput,
    @common.Body() data: InstrumentUpdateInput
  ): Promise<Instrument | null> {
    try {
      return await this.service.updateInstrument({
        where: params,
        data: data,
        select: {
          createdAt: true,
          currencyId: true,
          exchangeId: true,
          id: true,
          instrumentId: true,
          instrumentTypeId: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Instrument })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteInstrument(
    @common.Param() params: InstrumentWhereUniqueInput
  ): Promise<Instrument | null> {
    try {
      return await this.service.deleteInstrument({
        where: params,
        select: {
          createdAt: true,
          currencyId: true,
          exchangeId: true,
          id: true,
          instrumentId: true,
          instrumentTypeId: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/transactions")
  @ApiNestedQuery(TransactionFindManyArgs)
  async findTransactions(
    @common.Req() request: Request,
    @common.Param() params: InstrumentWhereUniqueInput
  ): Promise<Transaction[]> {
    const query = plainToClass(TransactionFindManyArgs, request.query);
    const results = await this.service.findTransactions(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        instrument: {
          select: {
            id: true,
          },
        },

        marketValueLocalCurrency: true,
        marketValuePortfolioCurrency: true,

        portfolio: {
          select: {
            id: true,
          },
        },

        quantity: true,
        transactionId: true,
        transactionType: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/transactions")
  async connectTransactions(
    @common.Param() params: InstrumentWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        connect: body,
      },
    };
    await this.service.updateInstrument({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/transactions")
  async updateTransactions(
    @common.Param() params: InstrumentWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        set: body,
      },
    };
    await this.service.updateInstrument({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/transactions")
  async disconnectTransactions(
    @common.Param() params: InstrumentWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        disconnect: body,
      },
    };
    await this.service.updateInstrument({
      where: params,
      data,
      select: { id: true },
    });
  }
}
